x-shared-env: &shared-env
  POSTGRES_HOST: ${POSTGRES_HOST:-db}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_DB: ${POSTGRES_DB:-db}
  POSTGRES_USER: ${PGUSER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

x-restart-policy: &restart-policy
  restart: unless-stopped

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  db:
    <<: *restart-policy
    image: postgres:15-alpine
    container_name: exam_postgres
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-db}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    command: >
      postgres 
      -c max_connections=${POSTGRES_MAX_CONNECTIONS:-100}
      -c shared_buffers=${POSTGRES_SHARED_BUFFERS:-128MB}
      -c work_mem=${POSTGRES_WORK_MEM:-4MB}
      -c maintenance_work_mem=${POSTGRES_MAINTENANCE_WORK_MEM:-64MB}
      -c effective_cache_size=${POSTGRES_EFFECTIVE_CACHE_SIZE:-1GB}
      -c wal_buffers=${POSTGRES_WAL_BUFFERS:-16MB}
      -c checkpoint_completion_target=${POSTGRES_CHECKPOINT_TARGET:-0.9}
      -c random_page_cost=${POSTGRES_RANDOM_PAGE_COST:-1.1}
      -c log_statement=${POSTGRES_LOG_STATEMENT:-mod}
      -c log_min_duration_statement=${POSTGRES_LOG_MIN_DURATION:-1000}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
      - ./volumes/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${PGUSER:-postgres} -d ${POSTGRES_DB:-db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: ${DB_MEMORY_LIMIT:-512M}
          cpus: '${DB_CPU_LIMIT:-0.5}'
        reservations:
          memory: ${DB_MEMORY_RESERVE:-256M}
          cpus: '${DB_CPU_RESERVE:-0.25}'
    logging: *default-logging
    networks:
      - app-network

  web:
    <<: *restart-policy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    environment:
      <<: *shared-env
      FLASK_ENV: ${FLASK_ENV:-production}
      FLASK_DEBUG: ${FLASK_DEBUG:-0}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s 
    networks:
      - app-network

  jenkins:
    <<: *restart-policy
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: exam_jenkins
    privileged: true
    user: "root:root"
    environment:
      JENKINS_OPTS: "${JENKINS_OPTS:---prefix=/jenkins}"
      JAVA_OPTS: >
        -Djenkins.install.runSetupWizard=false
        -Djava.awt.headless=true
        -Xmx${JENKINS_MEMORY:-1024}m
        -Xms${JENKINS_MEMORY_MIN:-512}m
        -XX:+UseG1GC
        -XX:+UseCompressedOops
        -Dfile.encoding=UTF-8
        -Dhudson.model.DirectoryBrowserSupport.CSP=""
      JENKINS_URL: "${JENKINS_URL:-https://jenkins.astrekoi.ru/}"
      JENKINS_PLUGINS: >
        workflow-aggregator:latest
        git:latest
        docker-workflow:latest
        docker-commons:latest
        pipeline-stage-view:latest
        blueocean:latest
        credentials:latest
        ssh-agent:latest
        ssh-credentials:latest
        workflow-api:latest
        workflow-basic-steps:latest
        workflow-cps:latest
        workflow-durable-task-step:latest
        workflow-job:latest
        workflow-support:latest
        workflow-scm-step:latest
        pipeline-model-definition:latest
        pipeline-utility-steps:latest
        pipeline-input-step:latest
        pipeline-milestone-step:latest
        pipeline-rest-api:latest
        pipeline-build-step:latest
        pipeline-graph-analysis:latest
        pipeline-stage-step:latest
        pipeline-maven:latest
        github:latest
        github-branch-source:latest
        github-api:latest
        git-client:latest
        branch-api:latest
        scm-api:latest
        matrix-auth:latest
        matrix-project:latest
        gradle:latest
        maven-plugin:latest
        nodejs:latest
        adoptopenjdk:latest
        junit:latest
        htmlpublisher:latest
        mailer:latest
        favorite:latest
        folders:latest
        timestamper:latest
        ws-cleanup:latest
        build-timeout:latest
        credentials-binding:latest
        plain-credentials:latest
        authentication-tokens:latest
        structs:latest
        workflow-multibranch:latest
        config-file-provider:latest
        token-macro:latest
        script-security:latest
        durable-task:latest
        display-url-api:latest
        checks-api:latest
        plugin-util-api:latest
        bootstrap5-api:latest
        jquery3-api:latest
        echarts-api:latest
        font-awesome-api:latest
        instance-identity:latest
        jackson2-api:latest
        gson-api:latest
        json-api:latest
        json-path-api:latest
        commons-lang3-api:latest
        commons-text-api:latest
        caffeine-api:latest
        okhttp-api:latest
        apache-httpcomponents-client-4-api:latest
        snakeyaml-api:latest
        variant:latest
        trilead-api:latest
        joda-time-api:latest
        jakarta-activation-api:latest
        jakarta-mail-api:latest
        jaxb:latest
        javadoc:latest
        ant:latest
    ports:
      - "${JENKINS_PORT:-9090}:8080"
      - "${JENKINS_AGENT_PORT:-50000}:50000"
    volumes:
      - ./volumes/jenkins/home:/var/jenkins_home
      - ./volumes/jenkins/plugins.txt:/usr/share/jenkins/ref/plugins.txt:ro
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost:8080/jenkins/login"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 240s
    logging: *default-logging
    networks:
      - app-network

  nginx:
    <<: *restart-policy
    image: nginx:${NGINX_VERSION:-1.25-alpine}
    container_name: exam_nginx
    environment:
      API_PORT: 5000
      JENKINS_PORT: 8080
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ${NGINX_TEMPLATE_SUFFIX:-.template}
      NGINX_ENVSUBST_OUTPUT_DIR: ${NGINX_OUTPUT_DIR:-/etc/nginx/conf.d}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:rw
      - ./volumes/nginx/logs:/var/log/nginx
    depends_on:
      web:
        condition: service_healthy
      jenkins:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/server/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: ${NGINX_MEMORY_LIMIT:-128M}
          cpus: '${NGINX_CPU_LIMIT:-0.2}'
    logging: *default-logging
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: ${NETWORK_NAME:-exam_app_network}
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET:-172.20.0.0/16}
